services:
  db:
    build: ./mariadb
    environment:
      DB_NAME: dolibarr
      DB_USER: dolibarr
      DB_PASSWORD: azerty1234
      DB_ROOT_PASSWORD: azerty1234
    volumes:
      - ./mariadb/data:/var/lib/mysql

  web:
    build: ./dolibarr
    environment:
      DOLI_ADMIN_LOGIN: admin
      DOLI_ADMIN_PASSWORD: azerty1234
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - dolibarr_docs:/var/www/documents
      - dolibarr_conf:/var/www/html/dolibarr/htdocs/conf

volumes:
  dolibarr_docs:
  dolibarr_conf: